version: "3.9"

networks:
  proxy:
    name: goat

services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    container_name: goat_core
    hostname: goat_core
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    networks:
      proxy:
